### ISSUE TITLE
Participación en Simposio de Desarrollo de Software

### ISSUE THREAD

**Issue by jaimelr** [UG-InternetApps/Temario#14]
Buenas noches profesor, mi compañera Verónica Montserrat Martínez Lona y yo (Jaime Loyola Rangel), asistiremos al 1er Simposio Internacional de Desarrollo de Software a realizarse en Yuriria, por lo que no podremos asistir a la clase del día de mañana.

**Comment by JuanCrg90** [comment]
Enterado, disfrutenlo. Mañana empezaré a ver versionamiento de código, para que se pongan al día.
