### ISSUE TITLE
Aviso/Recordatorio Clase

### ISSUE THREAD

**Issue by JuanCrg90** [UG-InternetApps/Temario#17]
Compañeros como les comenté el pasado Viernes, esta semana tendré que ausentarme por cuestiones de trabajo. Como acordamos

La Reposición de clase se dará el día martes 18 de octubre a las 8:00 PM por google hangout.

Pegaré la liga de la sala de llamada en este Issue para que estén pendientes, y le comenten a sus compañeros que no siguen el repositorio o que no hayan ido a clase el viernes pasado.

Clase de 7
https://hangouts.google.com/call/ggqdfs4sgne6jdt6jkbyxmca3ue

Clase de 8:
https://hangouts.google.com/call/nsxlqhhwnrgvpp6reyztxk24fie

Saludos.

**Comment by FranciscoRam** [comment]
Enterado

**Comment by TonyChagolla** [comment]
Enterado.

**Comment by jaimelr** [comment]
Enterado profesor, gracias.

**Comment by Andrea-DORIAN09** [comment]
Enterado

**Comment by vmmartinezlona** [comment]
Enterado c:

**Comment by IsabelVillafuerte** [comment]
Enterado

**Comment by JohnJasso** [comment]
Enterado.

**Comment by JuanCrg90** [comment]
Quien puede 7:30 en lugar de 8?

**Comment by IrepanBarAy** [comment]
Yo profe

**Comment by Erickglz25** [comment]
yo no tengo problema

**Comment by TonyChagolla** [comment]
Yo.

**Comment by JuanCrg90** [comment]
Ok daré una sesión de 7:30 a 8 y la segunda a las 8 (sera lo mismo, no se puede hacer mucho por video conferencia)

(Solo caben 10 usuarios por hangout)

**Comment by JuanCrg90** [comment]
https://hangouts.google.com/call/ggqdfs4sgne6jdt6jkbyxmca3ue

**Comment by JuanCrg90** [comment]
Clase de 8 aqui el link https://hangouts.google.com/call/nsxlqhhwnrgvpp6reyztxk24fie

**Comment by ErickMtz** [comment]
Profe mi intertet está muy lento y no me puedo conectar

**Comment by JuanCrg90** [comment]
No hay problema igual checa la tarea por favor
