### ISSUE TITLE
Fecha del examen

### ISSUE THREAD

**Issue by vmmartinezlona** [UG-InternetApps/Temario#18]
Disculpe profesor, no nos quedó claro la fecha del examen. ¿Será el viernes 11 o el 18?

**Comment by JuanCrg90** [comment]
18

_Juan Carlos Ruiz GonzálezSitio Web http://juancrg90.me/ | *_Twitter
https://twitter.com/juancrg90 | Linkedin
https://www.linkedin.com/in/juancrg90 | Github
http://github.com/JuanCrg90*
