### ISSUE TITLE
Aviso clase

### ISSUE THREAD

**Issue by JuanCrg90** [UG-InternetApps/Temario#20]
No alcanzó a llegar a clase, tengo que atender un pendiente.

Nos vemos el viernes para terminar la api.

Una disculpa.

**Comment by Andrea-DORIAN09** [comment]
Si, no se preocupe.
Nos vemos el viernes!

**Comment by JohnJasso** [comment]
Enterado.

**Comment by Erickglz25** [comment]
ok

**Comment by IsabelVillafuerte** [comment]
Ok, hasta el viernes!.
